# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dockergilsonravaiani

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dockergilsonravaiani.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8081096129a641a489d20c64c418fa0f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0520aa45bf6647d2a9c4d1e06583633c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dockergilsonravaiani.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8081096129a641a489d20c64c418fa0f }}/ravaiani:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dockergilsonravaiani'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_97d75bcf99f34aa985c0c1cf5d606354 }}
        images: 'dockergilsonravaiani.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8081096129a641a489d20c64c418fa0f }}/ravaiani:${{ github.sha }}'